### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by jetstarmedia** [opbeat/opbeat-node#153]
I saw this issue on most of my apps that i use opbeat. at the beginning i search the issue in my code but this behaviour and the same in all apps, some of the console apps and some of the rest apis. after each transcation end i receive this error: 
Error: read ECONNRESET
and its logged to my opbeat account, most of the usage in my account is this error thats looks its come from opbeat lib.

Thanks  

```
opbeat agent configured correctly { node: 'v7.10.0', agent: '4.13.3', org: 'XXXX', app: 'XXX', instrument: true } +0ms
 opbeat shimming Module._load function +11ms
 opbeat shimming http@7.10.0 module +60ms
 opbeat shimming http.Server.prototype.emit function +5ms
 opbeat shimming http.request function +0ms
 opbeat shimming http.ServerResponse.prototype.writeHead function +0ms
 opbeat shimming https@7.10.0 module +0ms
 opbeat shimming https.Server.prototype.emit function +1ms
 opbeat shimming hapi@16.1.1 module +60ms
 opbeat shimming hapi.Server.prototype.initialize +1ms
[03:56:38.686] MainProcess INIT
[03:56:38.709] MainProcess Server running at: http://0.0.0.0:3000
 opbeat intercepted request event call to http.Server.prototype.emit +29s
 opbeat setting transaction result { uuid: undefined, result: 200 } +2ms
 opbeat start transaction { uuid: '60b75196-91d8-4163-bfff-a072eb2856eb', name: undefined, type: undefined } +2ms
 opbeat init trace { uuid: '60b75196-91d8-4163-bfff-a072eb2856eb' } +1ms
 opbeat start trace { uuid: '60b75196-91d8-4163-bfff-a072eb2856eb', name: 'transaction', type: 'transaction' } +2ms
 opbeat received hapi onPreAuth event +18ms
 opbeat setting default transaction name: POST /pixel/?/? { uuid: '60b75196-91d8-4163-bfff-a072eb2856eb' } +1ms
[03:57:07.304] PcoptimProvider clientIP
[03:57:07.304] PcoptimProvider clientIP, found xx.xx.xx.xx
[03:57:07.304] PcoptimProvider this.clientIP = xx.xx.xx.xx
[03:57:07.305] PcoptimProvider clientIP
[03:57:07.305] PcoptimProvider clientIP, found xx.xx.xx.xx
[03:57:07.305] PcoptimProvider clientIP
[03:57:07.306] PcoptimProvider clientIP, found xx.xx.xx.xx
[03:57:07.309] PcoptimProvider write result { campaign: 'testcamp',
 ip: 'xx.xx.xx.xx',
 country: '',
 time: 1495425427 }
 opbeat received hapi onPreResponse event +31ms
 opbeat setting transaction result { uuid: '60b75196-91d8-4163-bfff-a072eb2856eb', result: 200 } +7ms
 opbeat ended trace { uuid: '60b75196-91d8-4163-bfff-a072eb2856eb', name: 'transaction', type: 'transaction', truncated: false } +10ms
 opbeat adding transaction to queue { uuid: '60b75196-91d8-4163-bfff-a072eb2856eb' } +0ms
 opbeat setting timer to flush transaction queue +1ms
 opbeat ended transaction { uuid: '60b75196-91d8-4163-bfff-a072eb2856eb', type: 'request', result: 200, name: 'POST /pixel/?/?' } +0ms
 opbeat flushing transaction queue +5s
 opbeat error while getting callsite source context: Can't get source context of a Node core callsite +18ms
 opbeat error while getting callsite source context: Can't get source context of a Node core callsite +1ms
 opbeat sending transactions to intake api +4ms
 opbeat transaction already ended - cannot build new trace { uuid: '60b75196-91d8-4163-bfff-a072eb2856eb' } +6ms
 opbeat intercepted call to http.request { uuid: null } +0ms
 opbeat logged transactions successfully +247ms
 opbeat intercepted request event call to http.Server.prototype.emit +14s
 opbeat setting transaction result { uuid: undefined, result: 200 } +0ms
 opbeat start transaction { uuid: 'a07d2ec5-0d4d-4d8c-b714-58985b34c0a4', name: undefined, type: undefined } +1ms
 opbeat init trace { uuid: 'a07d2ec5-0d4d-4d8c-b714-58985b34c0a4' } +0ms
 opbeat start trace { uuid: 'a07d2ec5-0d4d-4d8c-b714-58985b34c0a4', name: 'transaction', type: 'transaction' } +1ms
 opbeat received hapi onPreResponse event +17ms
 opbeat setting transaction result { uuid: 'a07d2ec5-0d4d-4d8c-b714-58985b34c0a4', result: 404 } +3ms
 opbeat could not extract route name from request { url: '/', type: 'undefined', null: false, route: false, regex: false, mountstack: false, uuid: 'a07d2ec5-0d4d-4d8c-b714-58985b34c0a4' } +3ms
 opbeat setting default transaction name: GET unknown route { uuid: 'a07d2ec5-0d4d-4d8c-b714-58985b34c0a4' } +0ms
 opbeat ended trace { uuid: 'a07d2ec5-0d4d-4d8c-b714-58985b34c0a4', name: 'transaction', type: 'transaction', truncated: false } +0ms
 opbeat adding transaction to queue { uuid: 'a07d2ec5-0d4d-4d8c-b714-58985b34c0a4' } +1ms
 opbeat setting timer to flush transaction queue +0ms
 opbeat ended transaction { uuid: 'a07d2ec5-0d4d-4d8c-b714-58985b34c0a4', type: 'request', result: 404, name: 'GET unknown route' } +0ms
logging error with Opbeat: { uuid: 'b5924aae-479e-4ae6-92df-7f2ca5b27c1b' }
Error: read ECONNRESET
   at exports._errnoException (util.js:1050:11)
   at TCP.onread (net.js:582:26)
   at TCP.instrumented (/opt/jetpixel/node_modules/opbeat/lib/instrumentation/index.js:102:27)
 opbeat error while getting callsite source context: Can't get source context of a Node core callsite +10s
 opbeat error while getting callsite source context: Can't get source context of a Node core callsite +1ms
 opbeat no active transaction found - cannot build new trace +10ms
 opbeat intercepted call to http.request { uuid: null } +0ms
Opbeat logged error successfully at https://opbeat.com/xxx-xxx-xxx/jetpixel/errors/shortcut/a1d711d6158b4011a2c1236f25d86ba8 { uuid: 'b5924aae-479e-4ae6-92df-7f2ca5b27c1b' }


 opbeat flushing transaction queue +51s
 opbeat error while getting callsite source context: Can't get source context of a Node core callsite +13ms
 opbeat error while getting callsite source context: Can't get source context of a Node core callsite +1ms
 opbeat sending transactions to intake api +0ms
 opbeat transaction already ended - cannot build new trace { uuid: 'a07d2ec5-0d4d-4d8c-b714-58985b34c0a4' } +6ms
 opbeat intercepted call to http.request { uuid: null } +1ms
 opbeat logged transactions successfully +208ms
 opbeat intercepted request event call to http.Server.prototype.emit +2s
 opbeat setting transaction result { uuid: undefined, result: 200 } +1ms
 opbeat start transaction { uuid: 'f09fb122-63f7-4010-bcd6-e82af39f1d6b', name: undefined, type: undefined } +0ms
 opbeat init trace { uuid: 'f09fb122-63f7-4010-bcd6-e82af39f1d6b' } +3ms
 opbeat start trace { uuid: 'f09fb122-63f7-4010-bcd6-e82af39f1d6b', name: 'transaction', type: 'transaction' } +0ms
 opbeat received hapi onPreAuth event +5ms
 opbeat setting default transaction name: POST /pixel/?/? { uuid: 'f09fb122-63f7-4010-bcd6-e82af39f1d6b' } +0ms
[03:58:28.889] PcoptimProvider clientIP
[03:58:28.890] PcoptimProvider clientIP, found xx.xx.xx.xx
[03:58:28.890] PcoptimProvider this.clientIP = xx.xx.xx.xx
[03:58:28.890] PcoptimProvider clientIP
[03:58:28.891] PcoptimProvider clientIP, found xx.xx.xx.xx
[03:58:28.891] PcoptimProvider clientIP
[03:58:28.891] PcoptimProvider clientIP, found xx.xx.xx.xx
[03:58:28.892] PcoptimProvider write result { campaign: 'testcamp',
 ip: 'xx.xx.xx.xx',
 country: '',
 time: 1495425508 }
 opbeat received hapi onPreResponse event +11ms
 opbeat setting transaction result { uuid: 'f09fb122-63f7-4010-bcd6-e82af39f1d6b', result: 200 } +2ms
 opbeat ended trace { uuid: 'f09fb122-63f7-4010-bcd6-e82af39f1d6b', name: 'transaction', type: 'transaction', truncated: false } +7ms
 opbeat adding transaction to queue { uuid: 'f09fb122-63f7-4010-bcd6-e82af39f1d6b' } +1ms
 opbeat setting timer to flush transaction queue +0ms
 opbeat ended transaction { uuid: 'f09fb122-63f7-4010-bcd6-e82af39f1d6b', type: 'request', result: 200, name: 'POST /pixel/?/?' } +0ms
logging error with Opbeat: { uuid: 'ed2d0274-4198-4338-ada7-b0a426247cc7' }
Error: read ECONNRESET
   at exports._errnoException (util.js:1050:11)
   at TCP.onread (net.js:582:26)
   at TCP.instrumented (/opt/jetpixel/node_modules/opbeat/lib/instrumentation/index.js:102:27)
 opbeat error while getting callsite source context: Can't get source context of a Node core callsite +29s
 opbeat error while getting callsite source context: Can't get source context of a Node core callsite +1ms
 opbeat no active transaction found - cannot build new trace +2ms
 opbeat intercepted call to http.request { uuid: null } +0ms
Opbeat logged error successfully at https://opbeat.com/xxx-xxx-xxx/jetpixel/errors/shortcut/0fe8e35e45d24604815e7d03500a413c { uuid: 'ed2d0274-4198-4338-ada7-b0a426247cc7' }
```

**Comment by jetstarmedia** [comment]
`  opbeat received hapi onPreResponse event +7ms
  opbeat setting transaction result { uuid: '998ee137-0e69-44a4-b374-6eff611e8a16', result: 200 } +4ms
  opbeat ended trace { uuid: '998ee137-0e69-44a4-b374-6eff611e8a16', name: 'transaction', type: 'transaction', truncated: false } +4ms
  opbeat adding transaction to queue { uuid: '998ee137-0e69-44a4-b374-6eff611e8a16' } +1ms
  opbeat setting timer to flush transaction queue +0ms
  opbeat ended transaction { uuid: '998ee137-0e69-44a4-b374-6eff611e8a16', type: 'request', result: 200, name: 'POST /pixel/?/?' } +1ms
  opbeat flushing transaction queue +5s
  opbeat error while getting callsite source context: Can't get source context of a Node core callsite +23ms
  opbeat error while getting callsite source context: Can't get source context of a Node core callsite +0ms
  opbeat error while getting callsite source context: Can't get source context of a Node core callsite +1ms
  opbeat error while getting callsite source context: Can't get source context of a Node core callsite +1ms
  opbeat error while getting callsite source context: Can't get source context of a Node core callsite +0ms
  opbeat sending transactions to intake api +7ms
  opbeat transaction already ended - cannot build new trace { uuid: '998ee137-0e69-44a4-b374-6eff611e8a16' } +4ms
  opbeat intercepted call to http.request { uuid: null } +1ms
  opbeat logged transactions successfully +207ms
  opbeat intercepted request event call to http.Server.prototype.emit +19s
  opbeat setting transaction result { uuid: undefined, result: 200 } +0ms
  opbeat start transaction { uuid: '2e0a8f7f-3a8a-4a2e-ab9f-2266ac7706eb', name: undefined, type: undefined } +1ms
  opbeat init trace { uuid: '2e0a8f7f-3a8a-4a2e-ab9f-2266ac7706eb' } +0ms
  opbeat start trace { uuid: '2e0a8f7f-3a8a-4a2e-ab9f-2266ac7706eb', name: 'transaction', type: 'transaction' } +0ms
  opbeat received hapi onPreResponse event +17ms
  opbeat setting transaction result { uuid: '2e0a8f7f-3a8a-4a2e-ab9f-2266ac7706eb', result: 404 } +4ms
  opbeat could not extract route name from request { url: '/', type: 'undefined', null: false, route: false, regex: false, mountstack: false, uuid: '2e0a8f7f-3a8a-4a2e-ab9f-2266ac7706eb' } +2ms
  opbeat setting default transaction name: GET unknown route { uuid: '2e0a8f7f-3a8a-4a2e-ab9f-2266ac7706eb' } +1ms
  opbeat ended trace { uuid: '2e0a8f7f-3a8a-4a2e-ab9f-2266ac7706eb', name: 'transaction', type: 'transaction', truncated: false } +0ms
  opbeat adding transaction to queue { uuid: '2e0a8f7f-3a8a-4a2e-ab9f-2266ac7706eb' } +0ms
  opbeat setting timer to flush transaction queue +0ms
  opbeat ended transaction { uuid: '2e0a8f7f-3a8a-4a2e-ab9f-2266ac7706eb', type: 'request', result: 404, name: 'GET unknown route' } +1ms
logging error with Opbeat: { uuid: 'dfcc4960-80e4-4ead-a1c4-f5b42155d6d9' }
Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
    at TCP.instrumented (/opt/jetpixel/node_modules/opbeat/lib/instrumentation/index.js:104:24)`

**Comment by watson** [comment]
Thanks for reaching out 😃

`ECONNRESET` means the other side of a TCP conversation abruptly closed its end of the connection. So it could be an outgoing HTTP request for instance that's aborted by the other end.

Since we instrument all outgoing TCP connections, we have injected out selfs into the call stack in which case you'll see us at some place in it. I know this can easily look like it's related to Opbeat, but it just meant that we monitored the connection that was aborted.

`ECONNRESET` errors can be fairly common depending on the stability of the network and the hosts you are talking.

I hope this answers your question. If not feel free to reopen the issue 😃

**Comment by jetstarmedia** [comment]
I replace Opbeat with Rollbar, no more errors

**Comment by AdriVanHoudt** [comment]
@jetstarmedia or Rollbar doesn't log it? :P
