### ISSUE TITLE
Opbeat graphql Error

### ISSUE THREAD

**Issue by cliedeman** [opbeat/opbeat-node#171]
Hello

I am getting the following error intermittently when opbeat is enabled.

```
TypeError: Cannot read property 'start' of null
    at wrappedExecute (/usr/src/app/node_modules/opbeat/lib/instrumentation/modules/graphql.js:115:12)
    at /usr/src/app/node_modules/express-graphql/dist/index.js:166:37
    at propagateObWrapper (/usr/src/app/node_modules/opbeat/lib/instrumentation/async-hooks.js:453:25)
    at instrumented (/usr/src/app/node_modules/opbeat/lib/instrumentation/index.js:102:27)
    at proxyWrapper (/usr/src/app/node_modules/opbeat/lib/instrumentation/async-hooks.js:462:30)
    at /usr/src/app/node_modules/opbeat/lib/instrumentation/async-hooks.js:490:70
    at instrumented (/usr/src/app/node_modules/opbeat/lib/instrumentation/index.js:102:27)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:208:7)
    at process.fallback (/usr/src/app/node_modules/opbeat/lib/instrumentation/async-hooks.js:514:17)
```

Node Version: 8.1.3

EDIT: I forgot to add...
Is there anything else I can check or enable to debug this further?

Thanks
Ciaran

**Comment by watson** [comment]
@cliedeman thank you so much for reporting this and sorry for the trouble 😬

It's fixed now in master and I'm just waiting for the tests to finish before publishing it to npm. I'll let you know once it's out 😃

**Comment by watson** [comment]
It's now released to npm as version 4.14.1

**Comment by cliedeman** [comment]
Thanks so much for fixing this.

Looking at the commit the query that previously failed will now not belong to any transaction?

But the request is coming in via express and should have a transaction? Or am I missing something

Ciaran

**Comment by watson** [comment]
Yes, in your case there was a transaction based on the incoming request. It then seems like you made a GraphQL query after the request had ended. It failed because we didn't expect that this function would be called after the transaction had ended. This is obviously possible, and it was a mistake that it was not guarded against.
