### ISSUE TITLE
Exception when calling captureError with Express

### ISSUE THREAD

**Issue by tchristian32** [opbeat/opbeat-node#225]
I am running node.js with express and if I call opbeat.captureError (to do my own logging of a handled error), I get the following exception:

```
Exception has occurred: TypeError
TypeError: Cannot read property 'request' of undefined
    at request (/.../node_modules/opbeat/lib/request.js:30:21)
    at Object.exports.error (/.../node_modules/opbeat/lib/request.js:44:3)
    at done (/.../node_modules/opbeat/lib/agent.js:226:44)
    at /.../node_modules/opbeat/lib/agent.js:242:7
    at /.../node_modules/opbeat/lib/parsers.js:46:7
    at /.../node_modules/after-all-results/index.js:20:25
    at opbeatCallbackWrapper (/.../node_modules/opbeat/lib/instrumentation/index.js:105:27)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    at process.fallback (/.../node_modules/opbeat/lib/instrumentation/patch-async.js:537:17)
```

**Comment by watson** [comment]
Opbeat has joined forces with [Elastic](https://www.elastic.co) and this agent is therefore deprecated. So I'll go ahead and close this issue.

I'm sorry that you encountered this error. Our new product is called [Elastic APM](https://www.elastic.co/solutions/apm), it's open source, and the [Node.js agent](https://github.com/elastic/apm-agent-nodejs) used there is based off this agent. Large parts of the source code have been rewritten since then, so the bug might have been fixed there already. If you're interested in trying out Elastic APM, we'd love your [feedback](https://discuss.elastic.co/c/apm).
