### ISSUE TITLE
Opbeat Crash - "next" function called after the final callback

### ISSUE THREAD

**Issue by iCyberon** [opbeat/opbeat-node#76]
Looks like `opbeat` is crashing my app. Here's the error (captured by opbeat):

```
Error: "next" function called after the final callback. Make sure all the calls to "next" are on the same tick
```

**node_modules/opbeat/node_modules/after-all/index.js** in **next**

```
    if (calls === 0) {
      done = true;
      afterAllCb();
    }
  });

  return function next(cb) {
    if (done) throw new Error(errorMessage);
    calls++;

    return function thecallback(err) {
      var args = arguments;
      if (isError(err) && !finalError) finalError = err;
      process.nextTick(function() {
        if (cb) cb.apply(null, args);
```

**Crash log**

```
App 39714 stderr: Error: "next" function called after the final callback. Make sure all the calls to "next" are on the same tick
App 39714 stderr:     at next (/[edited]/app/node_modules/opbeat/node_modules/after-all/index.js:25:21)
App 39714 stderr:     at /[edited]/app/node_modules/opbeat/lib/instrumentation/index.js:208:16
App 39714 stderr:     at Array.forEach (native)
App 39714 stderr:     at addStackTracesToTraceGroups (/[edited]/app/node_modules/opbeat/lib/instrumentation/index.js:202:10)
App 39714 stderr:     at Instrumentation._flush (/[edited]/app/node_modules/opbeat/lib/instrumentation/index.js:153:3)
App 39714 stderr:     at Instrumentation._send (/[edited]/app/node_modules/opbeat/lib/instrumentation/index.js:132:8)
App 39714 stderr:     at instrumented (/[edited]/app/node_modules/opbeat/lib/instrumentation/index.js:111:27)
App 39714 stderr:     at Timer.unrefdHandle (timers.js:312:14)
```

**Comment by watson** [comment]
@iCyberon Thanks for reporting this issue

- Which version of the agent are you running?
- Wild guess: Are you patching the `Array.prototype.forEach` function?

**Comment by watson** [comment]
@iCyberon Also, what version of `after-all` is installed in the `node_modules/after-all` folder?

**Comment by watson** [comment]
@iCyberon I'm going to close this issue for now to get things cleaned up a little around here. Feel free to reopen if this is still heppening 😃
